name: Waka Readme

on:
  schedule:
    - cron: '0 11 * * *'  # Runs daily at 12 AM IST
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_LANGUAGE: "False"
          SHOW_PROJECTS: "False"
          COMMIT_BY_ME: "True"
          SHOW_UPDATED_DATE: "False"
          COMMIT_USERNAME: "KavishkaSasindu"
          COMMIT_EMAIL: ${{ secrets.COMMIT_EMAIL }}
          SHOW_LINES_OF_CODE: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
